--
-- PostgreSQL database dump
--

\restrict ehZLapue2kM60I3567rVEy01CA16gdraEq2vK8uXsxHvrQEHu0W4UOdTXEic3V1

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: access; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.access (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    path character varying(255) NOT NULL
);


ALTER TABLE public.access OWNER TO postgres;

--
-- Name: access_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.access ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.access_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assignement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.assignement (
    end_date date,
    start_date date NOT NULL,
    employee_id bigint NOT NULL,
    responsability_id bigint,
    restaurant_id bigint NOT NULL
);


ALTER TABLE public.assignement OWNER TO postgres;

--
-- Name: employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee (
    id bigint NOT NULL,
    admin boolean DEFAULT false NOT NULL,
    hire_date date NOT NULL,
    image text,
    mail character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    surname character varying(255) NOT NULL,
    role_id bigint
);


ALTER TABLE public.employee OWNER TO postgres;

--
-- Name: employee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permission (
    role_id bigint NOT NULL,
    access_id bigint NOT NULL
);


ALTER TABLE public.permission OWNER TO postgres;

--
-- Name: responsability; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.responsability (
    id bigint NOT NULL,
    role character varying(255) NOT NULL
);


ALTER TABLE public.responsability OWNER TO postgres;

--
-- Name: responsability_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.responsability ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.responsability_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: restaurant; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurant (
    id bigint NOT NULL,
    image text,
    name character varying(255) NOT NULL,
    address_id bigint
);


ALTER TABLE public.restaurant OWNER TO postgres;

--
-- Name: restaurant_address; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurant_address (
    id bigint NOT NULL,
    address character varying(255) NOT NULL,
    city character varying(255) NOT NULL,
    cordx real,
    cordy real,
    postal_code character varying(255) NOT NULL
);


ALTER TABLE public.restaurant_address OWNER TO postgres;

--
-- Name: restaurant_address_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.restaurant_address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurant_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: restaurant_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.restaurant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role (
    id bigint NOT NULL,
    role_name character varying(255) NOT NULL
);


ALTER TABLE public.role OWNER TO postgres;

--
-- Name: role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: access access_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.access
    ADD CONSTRAINT access_pkey PRIMARY KEY (id);


--
-- Name: assignement assignement_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assignement
    ADD CONSTRAINT assignement_pkey PRIMARY KEY (employee_id, restaurant_id);


--
-- Name: employee employee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_pkey PRIMARY KEY (id);


--
-- Name: responsability responsability_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.responsability
    ADD CONSTRAINT responsability_pkey PRIMARY KEY (id);


--
-- Name: restaurant_address restaurant_address_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurant_address
    ADD CONSTRAINT restaurant_address_pkey PRIMARY KEY (id);


--
-- Name: restaurant restaurant_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurant
    ADD CONSTRAINT restaurant_pkey PRIMARY KEY (id);


--
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- Name: restaurant uk2b01rrbfd5g6hklh8ei57uhgn; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurant
    ADD CONSTRAINT uk2b01rrbfd5g6hklh8ei57uhgn UNIQUE (address_id);


--
-- Name: employee fk3046kvjyysq288vy3lsbtc9nw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT fk3046kvjyysq288vy3lsbtc9nw FOREIGN KEY (role_id) REFERENCES public.role(id);


--
-- Name: assignement fk3h5hmvl31c53k7mgwm91ex9st; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assignement
    ADD CONSTRAINT fk3h5hmvl31c53k7mgwm91ex9st FOREIGN KEY (responsability_id) REFERENCES public.responsability(id);


--
-- Name: assignement fk3lvdtaipmufrjpjvyiyec1or6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assignement
    ADD CONSTRAINT fk3lvdtaipmufrjpjvyiyec1or6 FOREIGN KEY (employee_id) REFERENCES public.employee(id);


--
-- Name: assignement fk7q6cx9rux8roqk1mhudma1erd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assignement
    ADD CONSTRAINT fk7q6cx9rux8roqk1mhudma1erd FOREIGN KEY (restaurant_id) REFERENCES public.restaurant(id);


--
-- Name: restaurant fkctnr9ijg8kk94ykc08sgdrbea; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurant
    ADD CONSTRAINT fkctnr9ijg8kk94ykc08sgdrbea FOREIGN KEY (address_id) REFERENCES public.restaurant_address(id);


--
-- Name: permission fkg9bqdtd19o5sb0bghyui3bcia; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT fkg9bqdtd19o5sb0bghyui3bcia FOREIGN KEY (access_id) REFERENCES public.access(id);


--
-- Name: permission fkrvhjnns4bvlh4m1n97vb7vbar; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT fkrvhjnns4bvlh4m1n97vb7vbar FOREIGN KEY (role_id) REFERENCES public.role(id);


--
-- PostgreSQL database dump complete
--

\unrestrict ehZLapue2kM60I3567rVEy01CA16gdraEq2vK8uXsxHvrQEHu0W4UOdTXEic3V1

