--
-- PostgreSQL database dump
--

\restrict WRXA6N0mOd1pL6qrBpSBxo0iygptGxmXSs4IMSjwjpi41dJzBolnxvqakSGAbqY

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: industrial_line; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.industrial_line (
    id bigint NOT NULL,
    code character varying(50) NOT NULL,
    created_at timestamp with time zone,
    description character varying(255),
    external_ref character varying(255),
    is_active boolean,
    name character varying(255) NOT NULL,
    nominal_cycle_s integer,
    owner character varying(255),
    process_type character varying(255),
    site character varying(255),
    technology character varying(255),
    updated_at timestamp with time zone
);


ALTER TABLE public.industrial_line OWNER TO postgres;

--
-- Name: industrial_line_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.industrial_line ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.industrial_line_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: machine; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.machine (
    id bigint NOT NULL,
    code character varying(10) NOT NULL,
    created_at timestamp(6) with time zone,
    description character varying(255),
    ip_address character varying(255),
    line_id integer NOT NULL,
    name character varying(255) NOT NULL,
    nominal_duration_s integer NOT NULL,
    opcua_endpoint character varying(255),
    order_index integer NOT NULL,
    plc_protocol character varying(255)
);


ALTER TABLE public.machine OWNER TO postgres;

--
-- Name: machine_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.machine ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.machine_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: part; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.part (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    external_part_id character varying(255) NOT NULL,
    finished_at timestamp(6) with time zone,
    line_id integer NOT NULL,
    status character varying(255) NOT NULL
);


ALTER TABLE public.part OWNER TO postgres;

--
-- Name: part_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.part ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.part_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plc_anomalies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.plc_anomalies (
    id bigint NOT NULL,
    anomaly_score double precision,
    burstiness double precision,
    confidence character varying(255),
    created_at timestamp with time zone,
    cycle integer NOT NULL,
    cycle_duration_s double precision,
    duration_overrun_s double precision,
    events_count integer,
    ewma_ratio double precision,
    has_step_error boolean,
    hawkes_score integer,
    n_step_errors integer,
    rate_ratio double precision,
    report_path character varying(255),
    rule_anomaly boolean NOT NULL,
    rule_reasons jsonb,
    severity character varying(255),
    status character varying(255),
    ts_detected timestamp with time zone NOT NULL,
    window_days integer,
    machine_id bigint,
    part_id bigint,
    event_id bigint,
    production_step_id bigint,
    workorder_id bigint
);


ALTER TABLE public.plc_anomalies OWNER TO postgres;

--
-- Name: plc_anomalies_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.plc_anomalies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plc_anomalies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plc_events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.plc_events (
    id bigint NOT NULL,
    code character varying(255),
    cycle integer,
    duration double precision,
    level character varying(255) NOT NULL,
    message character varying(255),
    payload jsonb,
    ts timestamp with time zone NOT NULL,
    machine_id bigint,
    part_id bigint,
    production_step_id bigint,
    workorder_id bigint
);


ALTER TABLE public.plc_events OWNER TO postgres;

--
-- Name: plc_events_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.plc_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plc_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: production_scenario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.production_scenario (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL,
    production_type character varying(255)
);


ALTER TABLE public.production_scenario OWNER TO postgres;

--
-- Name: production_scenario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.production_scenario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.production_scenario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: production_scenario_step; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.production_scenario_step (
    id bigint NOT NULL,
    step_order bigint NOT NULL,
    production_scenario_id bigint NOT NULL,
    production_step_id bigint NOT NULL
);


ALTER TABLE public.production_scenario_step OWNER TO postgres;

--
-- Name: production_scenario_step_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.production_scenario_step ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.production_scenario_step_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: production_step; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.production_step (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    description character varying(255),
    is_technical boolean,
    name character varying(255) NOT NULL,
    nominal_duration_s double precision NOT NULL,
    step_code character varying(10) NOT NULL,
    machine_id bigint NOT NULL
);


ALTER TABLE public.production_step OWNER TO postgres;

--
-- Name: production_step_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.production_step ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.production_step_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workorder; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workorder (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    finished_at timestamp(6) with time zone,
    nb_part_finish bigint,
    nb_part_rejected bigint,
    nb_part_scrapped bigint,
    nb_part_to_produce bigint,
    started_at timestamp(6) with time zone,
    status character varying(255) NOT NULL,
    production_scenario_id bigint
);


ALTER TABLE public.workorder OWNER TO postgres;

--
-- Name: workorder_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workorder ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workorder_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: industrial_line industrial_line_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.industrial_line
    ADD CONSTRAINT industrial_line_pkey PRIMARY KEY (id);


--
-- Name: machine machine_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.machine
    ADD CONSTRAINT machine_pkey PRIMARY KEY (id);


--
-- Name: part part_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.part
    ADD CONSTRAINT part_pkey PRIMARY KEY (id);


--
-- Name: plc_anomalies plc_anomalies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plc_anomalies
    ADD CONSTRAINT plc_anomalies_pkey PRIMARY KEY (id);


--
-- Name: plc_events plc_events_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plc_events
    ADD CONSTRAINT plc_events_pkey PRIMARY KEY (id);


--
-- Name: production_scenario production_scenario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_scenario
    ADD CONSTRAINT production_scenario_pkey PRIMARY KEY (id);


--
-- Name: production_scenario_step production_scenario_step_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_scenario_step
    ADD CONSTRAINT production_scenario_step_pkey PRIMARY KEY (id);


--
-- Name: production_step production_step_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_step
    ADD CONSTRAINT production_step_pkey PRIMARY KEY (id);


--
-- Name: machine uk_machine_code; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.machine
    ADD CONSTRAINT uk_machine_code UNIQUE (code);


--
-- Name: part uk_part_external_part_id; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.part
    ADD CONSTRAINT uk_part_external_part_id UNIQUE (external_part_id);


--
-- Name: industrial_line ukr7qa0e54n4ma7y8bnrkmft9i4; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.industrial_line
    ADD CONSTRAINT ukr7qa0e54n4ma7y8bnrkmft9i4 UNIQUE (code);


--
-- Name: workorder workorder_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workorder
    ADD CONSTRAINT workorder_pkey PRIMARY KEY (id);


--
-- Name: idx_industrial_line_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_industrial_line_code ON public.industrial_line USING btree (code);


--
-- Name: plc_anomalies fk2cavoauv2owau4x0ibwng1dsx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plc_anomalies
    ADD CONSTRAINT fk2cavoauv2owau4x0ibwng1dsx FOREIGN KEY (production_step_id) REFERENCES public.production_step(id);


--
-- Name: workorder fk650rmyc4q7hcnnelc4ry7bd8a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workorder
    ADD CONSTRAINT fk650rmyc4q7hcnnelc4ry7bd8a FOREIGN KEY (production_scenario_id) REFERENCES public.production_scenario(id);


--
-- Name: plc_anomalies fk732vn48s8fvnphkcyuhujijau; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plc_anomalies
    ADD CONSTRAINT fk732vn48s8fvnphkcyuhujijau FOREIGN KEY (part_id) REFERENCES public.part(id);


--
-- Name: production_step fk7w8w2epyjwuu52bsufvjr08ov; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_step
    ADD CONSTRAINT fk7w8w2epyjwuu52bsufvjr08ov FOREIGN KEY (machine_id) REFERENCES public.machine(id);


--
-- Name: production_scenario_step fk9tp9c90ja2y89i9cqy0axej5e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_scenario_step
    ADD CONSTRAINT fk9tp9c90ja2y89i9cqy0axej5e FOREIGN KEY (production_step_id) REFERENCES public.production_step(id);


--
-- Name: plc_events fk9wwh9fteaa5fv2lmgw08x1box; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plc_events
    ADD CONSTRAINT fk9wwh9fteaa5fv2lmgw08x1box FOREIGN KEY (workorder_id) REFERENCES public.workorder(id);


--
-- Name: plc_events fkc4if3gmkhjervb4a5hfhe1mxj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plc_events
    ADD CONSTRAINT fkc4if3gmkhjervb4a5hfhe1mxj FOREIGN KEY (production_step_id) REFERENCES public.production_step(id);


--
-- Name: plc_anomalies fkd1pa587o0ngvqu5b8jxnb47nn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plc_anomalies
    ADD CONSTRAINT fkd1pa587o0ngvqu5b8jxnb47nn FOREIGN KEY (machine_id) REFERENCES public.machine(id);


--
-- Name: plc_anomalies fkhu64n6gxhyiwhimov3trctgo2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plc_anomalies
    ADD CONSTRAINT fkhu64n6gxhyiwhimov3trctgo2 FOREIGN KEY (workorder_id) REFERENCES public.workorder(id);


--
-- Name: plc_anomalies fkj40s0rak23bx2yjg56vhfgxp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plc_anomalies
    ADD CONSTRAINT fkj40s0rak23bx2yjg56vhfgxp FOREIGN KEY (event_id) REFERENCES public.plc_events(id);


--
-- Name: plc_events fkj88x85eqeo8l179aomuiso22n; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plc_events
    ADD CONSTRAINT fkj88x85eqeo8l179aomuiso22n FOREIGN KEY (part_id) REFERENCES public.part(id);


--
-- Name: plc_events fkpjnqqghyjsih69seuftq2ohwm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plc_events
    ADD CONSTRAINT fkpjnqqghyjsih69seuftq2ohwm FOREIGN KEY (machine_id) REFERENCES public.machine(id);


--
-- Name: production_scenario_step fksxa8accx585rq1un8bp97xsk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_scenario_step
    ADD CONSTRAINT fksxa8accx585rq1un8bp97xsk FOREIGN KEY (production_scenario_id) REFERENCES public.production_scenario(id);


--
-- PostgreSQL database dump complete
--

\unrestrict WRXA6N0mOd1pL6qrBpSBxo0iygptGxmXSs4IMSjwjpi41dJzBolnxvqakSGAbqY

